### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by expert-soft** [Velvet78/1337#3]
Since last update I can't compile the wallet from source. 
**make: **\* [obj/rpcwallet.o] Error 1**
Please Tell me how to fix it.
uname -a
3.13.0-86-generic #130-Ubuntu SMP Mon Apr 18 18:27:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
uname -m
x86_64
Thanks in advance.

**Comment by Velvet78** [comment]
I think i forgot a space in rpcwallet.cpp. please try again. i added the function to clear orphans with the repairwallet command yesterday. if it keeps giving errors i'll revert back.

**Comment by expert-soft** [comment]
After the last 3 updates again error
**make: **\* [obj/rpcwallet.o] Error 1**

**Comment by Velvet78** [comment]
ok i reverted back the changes and compiled it on linux. seems to work ok now but please be aware that im still working on this new release. thanks for your feedback

**Comment by expert-soft** [comment]
Compiled successfully! Thank you!
